module.exports = [
  {
    id: 1,
    slug: "ultimate-button-clicker",
    title: "ULTIMATE BUTTON CLICKER",
    windowTitle: "ULTIMATE BUTTON CLICKER",
    desc: "Click the button. Keep clicking. How high can your score go?",
    tags: ["arcade"],
    thumb: "thumb-space",
    cardIconType: "image",
    cardIcon: "images/icons/ultimate-button-clicker.png",
    sidebarIcon: "👆",
    sidebarMeta: "ARCADE · CLICKER",
    plays: "—",
    rating: "★★★★★",
    ratingNum: "5.0",
    isNew: true,
    featured: true,
    iframeUrl: "https://white-bush-09dc4d31e.5.azurestaticapps.net/",
    accentColor: "#00ff88",
    placeholderBg: "radial-gradient(ellipse at center, #001a0d 0%, #000510 60%, #000 100%)",
    pulseBoxShadow1: "0 0 30px rgba(0,255,136,0.3)",
    pulseBoxShadow2: "0 0 50px rgba(0,255,136,0.6)",
    genre: "ARCADE / CLICKER",
    difficulty: "★☆☆☆☆",
    mobile: "✓ SUPPORTED",
    about: [
      "The button is right there. You know what to do.",
      "Click it. Watch the numbers go up. Click it faster. Upgrade your clicking power. Achieve button-clicking greatness.",
      "Simple premise, infinite satisfaction. How high can you go?"
    ],
    controls: [
      { key: "CLICK", label: "Click the button" },
      { key: "MOUSE", label: "Navigate menus" }
    ]
  },
  {
    id: 2,
    slug: "avoid-the-walls",
    title: "AVOID THE WALLS",
    windowTitle: "AVOID THE WALLS RUNNER",
    desc: "Race through tight corridors without touching the walls. One hit and it's over.",
    tags: ["action", "arcade"],
    thumb: "thumb-fight",
    cardIconType: "image",
    cardIcon: "images/icons/avoid-the-walls.png",
    sidebarIcon: "🏃",
    sidebarMeta: "ACTION · ARCADE",
    plays: "—",
    rating: "★★★★☆",
    ratingNum: "4.8",
    isNew: true,
    featured: false,
    iframeUrl: "https://easton873.github.io/avoid-the-walls-runner/",
    accentColor: "#ff3e6c",
    placeholderBg: "radial-gradient(ellipse at center, #1a0000 0%, #0d0005 60%, #000 100%)",
    pulseBoxShadow1: "0 0 30px rgba(255,62,108,0.3)",
    pulseBoxShadow2: "0 0 50px rgba(255,62,108,0.6)",
    genre: "ACTION / RUNNER",
    difficulty: "★★★★☆",
    mobile: "✓ SUPPORTED",
    about: [
      "The walls are closing in. Your only job: don't touch them.",
      "Navigate through tight corridors at increasing speeds. One brush against the wall and it's all over. Test your reflexes and see how far you can run.",
      "Easy to learn, brutally hard to master."
    ],
    controls: [
      { key: "←→", label: "Move left / right" },
      { key: "↑↓", label: "Move up / down" },
      { key: "MOUSE", label: "Navigate / steer" }
    ]
  },
  {
    id: 3,
    slug: "lemonade-stand",
    title: "LEMONADE STAND",
    windowTitle: "LEMONADE STAND",
    desc: "Run your own lemonade stand. Manage supplies, set prices, and turn a profit.",
    tags: ["strategy"],
    thumb: "thumb-dungeon",
    cardIconType: "emoji",
    cardIcon: "🍋",
    sidebarIcon: "🍋",
    sidebarMeta: "STRATEGY",
    plays: "—",
    rating: "★★★★☆",
    ratingNum: "4.7",
    isNew: false,
    featured: false,
    iframeUrl: "https://easton873.github.io/lemonade-stand/",
    accentColor: "#ffe033",
    placeholderBg: "radial-gradient(ellipse at center, #1a1200 0%, #0a0800 60%, #000 100%)",
    pulseBoxShadow1: "0 0 30px rgba(255,224,51,0.3)",
    pulseBoxShadow2: "0 0 50px rgba(255,224,51,0.6)",
    genre: "STRATEGY",
    difficulty: "★★☆☆☆",
    mobile: "✓ SUPPORTED",
    about: [
      "Start your empire one cup at a time.",
      "Manage your lemonade stand by setting the right price, buying supplies, and reading the weather. Too expensive and nobody buys. Too cheap and you lose money. Get it just right and watch the profits roll in.",
      "A classic business strategy game — simple to play, tricky to master."
    ],
    controls: [
      { key: "MOUSE", label: "All controls" },
      { key: "CLICK", label: "Confirm / buy" }
    ]
  },
  {
    id: 4,
    slug: "briannas-game",
    title: "BRIANNA'S GAME",
    windowTitle: "BRIANNA'S GAME",
    desc: "A special game made with love.",
    tags: ["arcade"],
    thumb: "thumb-platform",
    cardIconType: "image",
    cardIcon: "images/icons/briannas-game.png",
    sidebarIcon: "🎮",
    sidebarMeta: "ARCADE",
    plays: "—",
    rating: "★★★★★",
    ratingNum: "5.0",
    isNew: false,
    featured: false,
    iframeUrl: "https://green-forest-0fb98ed10.3.azurestaticapps.net/",
    accentColor: "#c864ff",
    placeholderBg: "radial-gradient(ellipse at center, #0d0020 0%, #060010 60%, #000 100%)",
    pulseBoxShadow1: "0 0 30px rgba(200,100,255,0.3)",
    pulseBoxShadow2: "0 0 50px rgba(200,100,255,0.6)",
    genre: "ARCADE",
    difficulty: "★★★☆☆",
    mobile: "✓ SUPPORTED",
    about: [
      "A special game made with love.",
      "Jump in and see what it's all about — there's only one way to find out."
    ],
    controls: [
      { key: "MOUSE", label: "Navigate / interact" },
      { key: "CLICK", label: "Confirm actions" }
    ]
  }
];
